Fix circular imports in the types
In particular you couldn't look up the urllib version, which was breaking
one of the tests:

$ python -c 'import urllib3; print(urllib3.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/alexwlchan/repos/urllib3/src/urllib3/__init__.py", line 15, in <module>
    from ._base_connection import _TYPE_BODY
  File "/Users/alexwlchan/repos/urllib3/src/urllib3/_base_connection.py", line 5, in <module>
    from .multipart import MultipartEncoder
  File "/Users/alexwlchan/repos/urllib3/src/urllib3/multipart/__init__.py", line 5, in <module>
    from .decoder import ImproperBodyPartContentError as ImproperBodyPartContentError
  File "/Users/alexwlchan/repos/urllib3/src/urllib3/multipart/decoder.py", line 8, in <module>
    from .. import response as _response
  File "/Users/alexwlchan/repos/urllib3/src/urllib3/response.py", line 46, in <module>
    from ._base_connection import _TYPE_BODY
ImportError: cannot import name '_TYPE_BODY' from partially initialized module 'urllib3._base_connection' (most likely due to a circular import) (/Users/alexwlchan/repos/urllib3/src/urllib3/_base_connection.py)